name: A2KitPvP
main: tk.applism.A2KitPvP
version: 1.0.0
api-version: 1.16
author: applearon
description: AOMS2 KitPvP plugin!
website: applism.tk

commands:
  kit:
    description: AOMS2 Kit command
    usage: /<command> <kit>
  a2join:
    description: Join Arena
    usage: /<command>
  spawn:
    description: Go back to Spawn
    usage: /<command>